### ISSUE TITLE
Failed post install for tyk-pro

### ISSUE THREAD

**Issue by husseinsa** [TykTechnologies/tyk-helm-chart#114]
### I am having an issue when installing the tyk-pro

![image](https://user-images.githubusercontent.com/22456321/114073222-0bb3ef00-9871-11eb-9d7d-5c45bb808f80.png)

Listing all the kuberenetes objects inside the namespace: `k get all -n tyk-pro`

![image](https://user-images.githubusercontent.com/22456321/114073604-78c78480-9871-11eb-8455-7624efea4b3f.png)

Investigating the failing pod that was created by the job

![image](https://user-images.githubusercontent.com/22456321/114073373-3736d980-9871-11eb-8bf1-dae150857b40.png)

**Comment by sedkis** [comment]
@husseinsa 
sorry for the delay.  Can you pull master and retry? This issue is solved in the latest branch

**Comment by vesko-tyk** [comment]
Issue is been resolved, hence closing it.
