### ISSUE TITLE
Improve bootstrap process

### ISSUE THREAD

**Issue by excieve** [TykTechnologies/tyk-helm-chart#12]
Currently we require manually running a script that calls dashboard admin APIs in order to bootstrap the deployment. It also writes a `Secret` manifest with dashboard user API credentials that needs to be applied as a part of another chart (`tyk-k8s`).

I believe this is not ideal, especially for automation or installing it as a Rancher catalogue app. In addition to this, calling dashboard API remotely for an ingress controller setup process is a bit idiosyncratic. This means one either needs another ingress controller/LB to expose it or rely on node ports, which might not be a desirable option if k8s cluster is running in a private section of a network and therefore nodes are not publicly exposed.

Perhaps running a job resource or an init container that does initial bootstrap and puts the result somewhere could improve it. Ideally, there also needs to be a way to pass the values to the ingress controller without manual intervention. E.g. it could automatically create a `Secret` resource that ingress controller would be able to discover.

**Comment by excieve** [comment]
I think this could be done quite nicely with a one-off `Job` resource as a post-install hook in Helm.

**Comment by vesko-tyk** [comment]
This is now implemented.
