### ISSUE TITLE
When using values.redis.addr, stray newline prevents last entry from working

### ISSUE THREAD

**Issue by mjpieters** [TykTechnologies/tyk-helm-chart#139]
The templates for `tyk-*.redis_url` add a stray `\n` newline character when `redis.addr` is set.

e.g. values containing:

```
redis:
  addrs:
  - redis-server-1:6379
  - redis-server-2:6379
```
results in

```
          - name: TYK_GW_STORAGE_ADDRS
            value: "redis-server-1:6379,redis-server-2:6379\n"
```

The stray newline breaks that entry. The newline comes from the `{{/* Adds support for ... }}` comment entries:

https://github.com/TykTechnologies/tyk-helm-chart/blob/aa9eee1d486858fa336b849b610ab2cfe3298349/tyk-pro/templates/_helpers.tpl#L58-L67

https://github.com/TykTechnologies/tyk-helm-chart/blob/aa9eee1d486858fa336b849b610ab2cfe3298349/tyk-headless/templates/_helpers.tpl#L41-L50

https://github.com/TykTechnologies/tyk-helm-chart/blob/aa9eee1d486858fa336b849b610ab2cfe3298349/tyk-hybrid/templates/_helpers.tpl#L42-L51

It can be fixed by replacing `{{/*` with `{{- /*`.

**Comment by christtyk** [comment]
@zalbiraw mind having a look?

**Comment by vesko-tyk** [comment]
@mjpieters Thank you for reporting this issue. This is now fixed in the latest release of our helm charts v0.9.1.
