### ISSUE TITLE
Helm charts for TIB

### ISSUE THREAD

**Issue by akashvyom** [TykTechnologies/tyk-helm-chart#15]
Helm chart for the deployment of Tyk Identity broker is not present in the repo. Similar to other components like gw, dash and pmp it would be great to have TIB deployment files also available with a flag if we want to install it.

**Comment by akashvyom** [comment]
@letzya I have written the files for TIB deployment, I can raise a PR for this enhancement.

**Comment by tan31989** [comment]
@letzya can this be reviewed?
