### ISSUE TITLE
Chart not found

### ISSUE THREAD

**Issue by ayinlaaji** [TykTechnologies/tyk-helm-chart#16]
helm repo add tc http://trusted-charts.stackpoint.io

Error: Looks like "http://trusted-charts.stackpoint.io" is not a valid chart repository or cannot be reached: Get http://trusted-charts.stackpoint.io/index.yaml: read tcp 192.168.0.172:51140->216.58.223.240:80: read: connection reset by peer

**Comment by lonelycode** [comment]
@ayinlaaji I can't replicate this, have you tried recently? Also this isn't actually required, this repo just happens to have some easy to install mongo and redis charts. You can use any redis or mongoDB chart to get those running.
