### ISSUE TITLE
Add ability to use a custom default certificate

### ISSUE THREAD

**Issue by seanhoughton** [TykTechnologies/tyk-helm-chart#168]
I've added this feature in https://github.com/TykTechnologies/tyk-helm-chart/pull/167

It might be useful to further improve this implementation by switching to TLS type certificates which would require altering the conf file.

**Comment by sedkis** [comment]
Hi @seanhoughton ,

Thanks for your contribution!

Would this be more or less difficult than simply replacing the contents of `tyk-default-cert` with the user's own key files?

**Comment by seanhoughton** [comment]
When using a gitops pipeline to deploy k8s objects and HelmReleases (e.g. Flux) all resources are managed explicitly so having two colliding objects defined simultaneously doesn't work.

**Comment by caroltyk** [comment]
We have implemented this in our new chart here:
https://github.com/TykTechnologies/tyk-charts/tree/main/tyk-oss#enabling-tls
