### ISSUE TITLE
More document on injector?

### ISSUE THREAD

**Issue by fr0der1c** [TykTechnologies/tyk-helm-chart#17]
Hi, I'm new to Tyk and I'm considering using it for my project. Is there any more document on service mesh injector other than the README.md in this repository? The readme only mentioned the `injector.tyk.io/inject` and `injector.tyk.io/route` annotation. Is there any other annotations? Where can I find them?

**Comment by joshblakeley** [comment]
It's in an alpha state at the moment - what do you want to achieve?

**Comment by fr0der1c** [comment]
Hi Josh,
Thank you for replying. I'm new to the concept of Service Mesh and just want to try it out on my own project to see what it can bring to me. I thought it is useable since it's on the master branch and it's already on readme. There isn't really something I want to achieve at the moment. Maybe I should wait for a bit:)
