### ISSUE TITLE
The default configuration for tyk-headless has no persistence and no API consistency

### ISSUE THREAD

**Issue by seanhoughton** [TykTechnologies/tyk-helm-chart#170]
The headless chart creates the api gateways as a DaemonSet with emptyDir storage. This means multiple gateways pods, each with their own independent view of state. When the API is used to create apps via tyk-sync, tyk-operator, or manually with curl the result is a mess of inconsistent state depending upon which pod requests are routed to. Additionally, when a pod is destroyed and recreated all of its state disappears.

I would suggest a short term fix of switching the headless chart to default to a `Deployment` with `replicaCount=1` and add a PVC for storage rather than an emptyDir. This would make the default install function correctly, although with scale limited to one pod.

The open source edition of Tyk seems to be architecturally limited to a single instance of the gateway pod without some additional "config has changed" events or hooks to trigger config reloads on all pods.

**Comment by kiwiidb** [comment]
Mounting a secret that contains the API definitions does not seem to be supported by the current chart.
Why are the mounts being done in the `setup-directories` initContainer instead of the actual container?

**Comment by caroltyk** [comment]
Hi @seanhoughton 

We have added support for persistent volume mount in v0.14.0 through this PR https://github.com/TykTechnologies/tyk-helm-chart/pull/264.

There is a demo of how to use the latest helm chart + PVC to synchronise multiple gateways too:
https://github.com/buraksekili/multiple-tyk-gateway

If you're an Open Source user, please take a look at our new Helm Charts which will be continued enhanced with latest feature: https://github.com/TykTechnologies/tyk-charts/tree/main/tyk-oss
