### ISSUE TITLE
Change ingress resource definition to use networking.k8s.io/v1 instead of v1beta1

### ISSUE THREAD

**Issue by raman-nbg** [TykTechnologies/tyk-helm-chart#174]
Currently, the ingress resources that are deployed with the `tyk-pro` helm chart, deploy ingresses that use the `networking.k8s.io/v1beta1` api (e.g. look at https://github.com/TykTechnologies/tyk-helm-chart/blob/master/tyk-pro/templates/ingress-dash.yaml#L4).

This api version is deprecated and will be removed with K8s v1.22+. The ingress resources should be adopted to use the api version `v1`.

**Comment by n2linux** [comment]
Hi @raman-nbg thanks for letting us know - the team will take a look at this.

**Comment by cherrymu** [comment]
Thanks @chrisz , we are working on it and will fix this soon to support backward compatibility also along with latest k8's versions

**Comment by vesko-tyk** [comment]
Implemented in this PR: https://github.com/TykTechnologies/tyk-helm-chart/pull/184
