### ISSUE TITLE
ERROR: After approving csr tyk-k8s-svc.tyk, the signed certificate did not appear on the resource. Giving up after 10 attempts.

### ISSUE THREAD

**Issue by fr0der1c** [TykTechnologies/tyk-helm-chart#18]
I'm just getting started with this helm chart. After `helm install`, it shows several steps to do. One of them is:
```
3. Prepare the SSL and CA bundle for webhook

./tyk-k8s/webhook/create-signed-cert.sh -n tyk
cat ./tyk-k8s/webhook/mutatingwebhook.yaml | ./tyk-k8s/webhook/webhook-patch-ca-bundle.sh > ./tyk-k8s/webhook/mutatingwebhook-ca-bundle.yaml
```

However, when running the first command. I run into an error:
```
[root@VM_1_16_centos tyk-helm-chart]# ./tyk-k8s/webhook/create-signed-cert.sh -n tyk
creating certs in tmpdir /tmp/tmp.OMHaltlIKA
Generating RSA private key, 2048 bit long modulus
....+++
......................................+++
e is 65537 (0x10001)
certificatesigningrequest.certificates.k8s.io "tyk-k8s-svc.tyk" created
NAME              AGE       REQUESTOR   CONDITION
tyk-k8s-svc.tyk   1s        admin       Pending
certificatesigningrequest.certificates.k8s.io "tyk-k8s-svc.tyk" approved
ERROR: After approving csr tyk-k8s-svc.tyk, the signed certificate did not appear on the resource. Giving up after 10 attempts.
```

My question is:
1. What is webhook and how is that related to sidecar-injector?
2. What can I do to solve the error?

Thanks in advance.

**Comment by joshblakeley** [comment]
Hi

The mutating webhook is what carries out the sidecar injection in the cluster - the controller needs the cert to have permission to carry out these mutating actions.

What k8s version are you running?

**Comment by fr0der1c** [comment]
Hi Josh,
Thanks for your explanation. I'm using k8s 1.10.5.

**Comment by krijohs** [comment]
I'm getting the same error when running tyk helm chart on a cluster created with rancher rke.
The csr does never set the `status.certificate` so it's missing. How can I solve this?

**Comment by lonelycode** [comment]
@krijohs are you using RBAC?

**Comment by fr0der1c** [comment]
Yes. I'm using RBAC.
