### ISSUE TITLE
Add tag v0.9.4 to current master

### ISSUE THREAD

**Issue by beng90** [TykTechnologies/tyk-helm-chart#186]
Please add tag to current version in master because in v0.9.3 there is a bug in file:
https://github.com/TykTechnologies/tyk-helm-chart/blob/master/tyk-headless/templates/secrets-mounts.yaml

In master file is fixed

Error while apply
Error: template: tyk-headless/templates/secrets-mounts.yaml:10:49: executing "tyk-headless/templates/secrets-mounts.yaml" at <include "tyk-pro.fullname" $>: error calling include: template: no template "tyk-pro.fullname" associated with template "gotpl"

**Comment by vesko-tyk** [comment]
Version 0.9.4 is now released.
