### ISSUE TITLE
Can I secure Tyk Dashboard with HTTPS?

### ISSUE THREAD

**Issue by fr0der1c** [TykTechnologies/tyk-helm-chart#19]
By default, the dashboard uses plain HTTP. Can I attach an SSL certificate?

**Comment by lonelycode** [comment]
It's exposed as a `NodePort` at the moment, the simplest thing to do would be to swap it to a service and run it through an ingress. The chart itself doesn't expose this capability yet.

**Comment by excieve** [comment]
The chart supports all service types and has an optional ingress for both the dashboard and the portal. So that's an option.

It's also beneficial to be able to configure a TLS listener on the dashboard directly so will keep this open for now.
