### ISSUE TITLE
[TT-4979] - Add group_id to (Hybrid) Helm charts for multi cluster MDCB deployments

### ISSUE THREAD

**Issue by rewsmith** [TykTechnologies/tyk-helm-chart#193]
When running Tyk MDCB Slave Gateways, or Tyk Hybrid Worker Gateways, APIs aren’t always loaded in Gateway clusters.  This happens when running 2 or more isolated Gateway clusters, each having their own redis, but group_id isn't set.

group_id should be added to the hybrid chart, with an appropriate comment to explain why it is required.

**Comment by vesko-tyk** [comment]
PR is now merged and release into v0.9.5 of the hybrid chart.
