### ISSUE TITLE
Helm Chart tyk-headless-0.11.0 is missing

### ISSUE THREAD

**Issue by einhorneyal** [TykTechnologies/tyk-helm-chart#240]
Hi, 

The tyk-headless-0.11.0 chart is missing: 
"error: failed to fetch https://helm.tyk.io/public/helm/charts/tyk-headless-0.11.0.tgz : 404 Not Found"
https://github.com/TykTechnologies/tyk-helm-chart/actions/runs/3289241701/jobs/5420537536

**Comment by andrei-tyk** [comment]
Hello @einhorneyal , thank you for submitting this issue. We are currently investigating and we'll back with a message when it's fixed.

**Comment by andrei-tyk** [comment]
@einhorneyal can you please check now?

**Comment by einhorneyal** [comment]
works great now, thanks!
