### ISSUE TITLE
TT-7322 Allow ENV's to use secret values

### ISSUE THREAD

**Issue by oc-christopher-billett** [TykTechnologies/tyk-helm-chart#246]
Whilst trying to use a secret value as an ENV I noticed that the `extraEnvs` is written to fix just a name/value and will not allow for the use `valueFrom`. This is very limiting when storing values in secrets. I'm my example I'm creating an external redis cluster using IaC and push the endpoint and password into a secret. I then wish to pull in the endpoint url without hardcoding the values file.

**deployment-gw-repset.yaml**

``` 
{{- if .Values.gateway.extraEnvs }}
{{- range $env := .Values.gateway.extraEnvs }}
  - name: {{ $env.name }}
    value: {{ $env.value | quote }}
{{- end }}
{{- end }}```

**Comment by buraksekili** [comment]
hi @oc-christopher-billett, have you tried setting your secrets via `secrets.useSecretName` (https://github.com/TykTechnologies/tyk-helm-chart/blob/master/tyk-headless/values.yaml#L24) field?

**Comment by oc-christopher-billett** [comment]
> hi @oc-christopher-billett, have you tried setting your secrets via `secrets.useSecretName` (https://github.com/TykTechnologies/tyk-helm-chart/blob/master/tyk-headless/values.yaml#L24) field?

Indeed, i'm using this for the `redisPass` and it's the same secret I was wanting to pull the additional ENV from. This secret is only used by the chart for specific items like the redis password env shown below that call out the use of the named secret

```
          - name: TYK_GW_STORAGE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.secrets.useSecretName }} {{ .Values.secrets.useSecretName }} {{ else }} secrets-{{ include "tyk-headless.fullname" . }} {{ end}}
                key: redisPass

**Comment by buraksekili** [comment]
As you said, we use `secrets.useSecretName` for specific environment variables. Sorry if i misunderstood your request but Isn't `secrets.useSecretName` helpful for setting redisPassword through? Or do you want to achieve something else? Apart from setting redis passport, what environment variables would you like to set from secret? 
If the current approach, I mean `secrets.useSecretName`, is not capable of what you want to do, we can prioritize your request for future releases.

**Comment by oc-christopher-billett** [comment]
@buraksekili In true gitops fashion when using tools such as ArgoCD I need to pass in as much as a variable as possible.

I create redis using terraform and populate a secret on the k8's cluster with the password and the endpoint in. I used the `secrets.useSecretName` to get the password, but want to populate the value for ENV `TYK_GW_STORAGE_HOST` from the secret as follows:

```
tyk-headless:
  gateway:
    extraEnvs:
    - name: TYK_GW_STORAGE_HOST
      valueFrom:
        secretKeyRef:
          name: tyk-secret-name
          key: redisEndpoint
```
Not having the ability to use the `valueFrom` option in the `extraEnvs` or even the ability to use a `csi` in the volume  (another issue in itself) can be limiting, which then forces hardcoded values.

**Comment by buraksekili** [comment]
@oc-christopher-billett, thank you for providing great details. let's keep this issue open until a fix is raised for this. we will work on this as soon as we can. again, thank you :)
