### ISSUE TITLE
Move configs from file to values

### ISSUE THREAD

**Issue by cuttingedge1109** [TykTechnologies/tyk-helm-chart#253]
## Description
Now all config files are rendered using `Files.Glob(pattern string)`. It means configs are the part of chart source, not configurable values. It makes it impossible to keep custom configurations per env separate from chart manifests.

## Expected result
Keep configs in the `values.yaml` so user can keep only values override file.

## Proposed solutions
Add all configs into values and use `toJson` instead of `Files.Glob(pattern string)`.

**Comment by caroltyk** [comment]
Hi @cuttingedge1109 , thank you for the suggestion. We are refactoring our charts and in our new version, the use of config files will be deprecated to avoid confusion. All configs will be kept in values.yaml

**Comment by caroltyk** [comment]
Please try out our new charts here: https://github.com/TykTechnologies/tyk-charts

Currently, Tyk OSS chart is available. You can also deploy a MDCB/Cloud data plane using tyk-mdcb-data-plane. The Tyk Pro self managed chart and MDCB control plane chart is on the way!
