### ISSUE TITLE
tyk-headless: mounting files into gateway component fails (include error)

### ISSUE THREAD

**Issue by bastianbeier** [TykTechnologies/tyk-helm-chart#256]
Hello,
I tried mounting a file to create an API in file-based mode. But when I run helm install it fails with following message:
`Error: INSTALLATION FAILED: template: tyk-headless/templates/deployment-gw-repset.yaml:46:49: executing "tyk-headless/templates/deployment-gw-repset.yaml" at <include (print "mounts/%s" $secret.filename) .>: error calling include: template: no template "mounts/%stestapi.json" associated with template "gotpl`

## Steps to reproduce:
1. checkout tag v0.13.2
2. add testapi to the values.yaml into the gateway.mounts array
 ```
 - name: testapi
    filename: testapi.json
    mountPath: /opt/tyk-gateway
 ```
3. add testapi.json to mounts directory
 ```
{
    "name": "Test-API",
    "api_id": "1",
    "org_id": "1",
    "use_keyless": true,
    "definition": {
        "location": "header",
        "key": "x-api-version"
    },
    "version_data": {
        "not_versioned": true,
        "versions": {
            "Default": {
                "name": "Default",
                "use_extended_paths": true
            }
        }
    },
    "proxy": {
        "listen_path": "/google",
        "target_url": "https://www.google.com",
        "strip_listen_path": true
    },
    "active": true
}
 ```
5. run `helm install test . ` (inside tyk-headless dir)
 
## Expected result
helm install succeeds and file is mounted

## Actual result
`Error: INSTALLATION FAILED: template: tyk-headless/templates/deployment-gw-repset.yaml:46:49: executing "tyk-headless/templates/deployment-gw-repset.yaml" at <include (print "mounts/%s" $secret.filename) .>: error calling include: template: no template "mounts/%stestapi.json" associated with template "gotpl`

**Comment by buraksekili** [comment]
hi @bastianbeier, thank you for raising this issue. I am able to reproduce this error on my side as well. I'll create a ticket for the team internally. We always welcome contributions, if you have a solution for the problem.

**Comment by bastianbeier** [comment]
Hi @buraksekili,
Thank you for the quick reply.
Sadly I am not having a solution for the problem.
I am doing a workaround using the Tyk Gateway REST API for config.

Best regards
Bastian

**Comment by buraksekili** [comment]
> Sadly I am not having a solution for the problem.

@bastianbeier no worries, again thank you for informing us about the issue.

> I am doing a workaround using the Tyk Gateway REST API for config.

that's great if you overcome the problem with a workaround. we hope to come up with a solution for the next releases. let's keep this issue until we have a fix for the issue.

**Comment by buraksekili** [comment]
hi @bastianbeier, thank you again for raising this issue. we've merged a PR to fix this issue. Hope, it'll be available in the next release.
