### ISSUE TITLE
bootstrap.sh ValueError: Invalid control character at: line 1 column 33 (char 32)

### ISSUE THREAD

**Issue by kevev** [TykTechnologies/tyk-helm-chart#27]
We have installed the dashboard RPMs from Tyk Yum repo onto RHEL 7 x86_64.
Receiving this error below. The bootstrap.sh script never sets variable $USER_AUTH_CODE, so I am wondering how this gets set.

Seems similar to this issue: https://github.com/TykTechnologies/tyk-helm-chart/issues/10

`/opt/tyk-dashboard/install/bootstrap.sh localhost
Found Python interpreter at: /bin/python

Creating Organisation
ORG DATA: {"Status":"OK","Message":"Org created","Meta":"5d3624e60f48ec660c7d9173"}
ORG ID: 5d3624e60f48ec660c7d9173

Adding new user
USER_AUTH_CODE =
USER AUTHENTICATION CODE:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 33 (char 32)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
ERROR: Unable to parse JSON`

**Comment by asoorm** [comment]
@kevev so in your case, you are not using helm? You deployed the dashboard straight to RHEL?

Do you have the gateway running and connected to the dash? Can you share gateway & dashboard logs at this time?

**Comment by kevev** [comment]
> @kevev so in your case, you are not using helm? You deployed the dashboard straight to RHEL?
> 
> Do you have the gateway running and connected to the dash? Can you share gateway & dashboard logs at this time?

Not using help. Yes, deployed to RHEL.

We do not have any gateway or dashboard logs as we are still attempting to set this Tyk env up.

**Comment by asoorm** [comment]
It looks like your license key is invalid: `License error:token contains an invalid number of segments`

https://tyk.io/docs/get-started/with-tyk-on-premise/installation/redhat-rhel-centos/dashboard/#step-8-enter-dashboard-license

**Comment by kevev** [comment]
License has been added. Same error.

`[root@tyktest-mgmt01 ~]# /opt/tyk-dashboard/install/bootstrap.sh tyktest-mgmt01.rbfcu.local
Found Python interpreter at: /bin/python

Creating Organisation
ORG DATA: {"Status":"Error","Message":"Failed to save new Org object to DB","Meta":null}
ORG ID: None

Adding new user
USER_AUTH_CODE =
USER AUTHENTICATION CODE:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 43 (char 42)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
ERROR: Unable to parse JSON
[root@tyktest-mgmt01 ~]# systemctl status tyk-dashboard
● tyk-dashboard.service - Tyk API Dashboard
   Loaded: loaded (/usr/lib/systemd/system/tyk-dashboard.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-07-23 10:07:50 CDT; 1min 17s ago
 Main PID: 20847 (tyk-analytics)
   CGroup: /system.slice/tyk-dashboard.service
           └─20847 /opt/tyk-dashboard/tyk-analytics --conf /opt/tyk-dashboard/tyk_analytics.conf

Jul 23 10:07:50 tyktest-mgmt01.rbfcu.local tyk-analytics[20847]: time="Jul 23 10:07:50" level=info msg="Socket server started"
Jul 23 10:07:50 tyktest-mgmt01.rbfcu.local tyk-analytics[20847]: time="Jul 23 10:07:50" level=info msg="--> Standard listener (http) for UI notifications" addr=":5000"
Jul 23 10:07:50 tyktest-mgmt01.rbfcu.local tyk-analytics[20847]: time="Jul 23 10:07:50" level=info msg="Adding available nodes..."
Jul 23 10:07:50 tyktest-mgmt01.rbfcu.local tyk-analytics[20847]: time="Jul 23 10:07:50" level=info msg="--> Standard listener (http) for dashboard and API"
Jul 23 10:07:50 tyktest-mgmt01.rbfcu.local tyk-analytics[20847]: time="Jul 23 10:07:50" level=info msg="Starting zeroconf heartbeat"
Jul 23 10:07:50 tyktest-mgmt01.rbfcu.local tyk-analytics[20847]: time="Jul 23 10:07:50" level=info msg="Starting notification handler for gateway cluster"
Jul 23 10:07:50 tyktest-mgmt01.rbfcu.local tyk-analytics[20847]: time="Jul 23 10:07:50" level=info msg="Loading routes..."
Jul 23 10:09:04 tyktest-mgmt01.rbfcu.local tyk-analytics[20847]: time="Jul 23 10:09:04" level=error msg="Insert failed for org"
Jul 23 10:09:04 tyktest-mgmt01.rbfcu.local tyk-analytics[20847]: time="Jul 23 10:09:04" level=error msg="not found"
Jul 23 10:09:04 tyktest-mgmt01.rbfcu.local tyk-analytics[20847]: time="Jul 23 10:09:04" level=error msg="Failed to save new Org object to DB"`

**Comment by kevev** [comment]
Upgraded to latest release of tyk-dashbaord rpm via yum.

`[root@tyktest-mgmt01` ~]# /opt/tyk-dashboard/install/bootstrap.sh tyktest-mgmt01.rbfcu.local
Found Python interpreter at: /bin/python

Creating Organisation
ORG DATA: {"Status":"Error","Message":"Failed to save new Org object to DB","Meta":null}
ORG ID: None

Adding new user
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 34 (char 33)
ERROR: Unable to parse JSON``

**Comment by kevev** [comment]
We figured it out. The config had invalid db connection string.
