### ISSUE TITLE
Make bootstrap images configurable for tyk-pro

### ISSUE THREAD

**Issue by Guitarkalle** [TykTechnologies/tyk-helm-chart#290]
The images for the bootstrap jobs in the tyk-pro chart are hard coded. We use private registries with mirrored images and cannot use the chart as is now since they are not configurable in the Value files.

Suggest adding values for these as for all other images in the chart.

**Comment by buraksekili** [comment]
hi @Guitarkalle, thanks for raising this! We are in the middle of switching to our new Helm charts, [tyk-charts](https://github.com/TykTechnologies/tyk-charts/). However, the issue you mentioned is not resolved yet, even for the new one - it is on our backlog. If you are willing to contribute, I am more than happy to help.

**Comment by Guitarkalle** [comment]
@buraksekili 
Thank you! Can I make a PR to this repo?

**Comment by buraksekili** [comment]
Let's resolve the issue in this repo. Then, if you want, you can move your changes to the new one as well. Let me know if you need anything. Thanks again!

**Comment by Guitarkalle** [comment]
@buraksekili I made a PR: https://github.com/TykTechnologies/tyk-helm-chart/pull/291/files
let me know if I did anything incorrectly. I couldn't find any appropriate documentation that would need updating.

I also changed the structure slightly for the existing bootstrap job values so it has it's own section

**Comment by caroltyk** [comment]
@Guitarkalle This change is available in our latest Helm Chart release.

Please note that Tyk is working on a better new helm chart available at https://github.com/TykTechnologies/tyk-charts and the current `tyk-pro` chart will be deprecated once the new chart is stabilised.
