### ISSUE TITLE
bootstrap script assumes http

### ISSUE THREAD

**Issue by tesharp** [TykTechnologies/tyk-helm-chart#32]
We use the ingress resource for dashboard to expose it public, and ssl offloading in WAF. When running bootstrap script it tries to connect to the internal pod, but we would like it to just connect to the public dashboard api. However script assumes http and its exposed on https. Script works by changing all calls from http to https, so should be possible to do this with some option so we dont have to change script

**Comment by WoodProgrammer** [comment]
Hi @tesharp I have opened new PR for that; https://github.com/TykTechnologies/tyk-helm-chart/pull/36 @furkansenharputlu @excieve

**Comment by excieve** [comment]
This has been merged, closing. Thanks @WoodProgrammer!
