### ISSUE TITLE
Run containers as non-root by default

### ISSUE THREAD

**Issue by excieve** [TykTechnologies/tyk-helm-chart#39]
Change the templates to run all the Tyk containers as non-root user by default, but keep an option to change the user for the gateway since there might be a legitimate use case with a host network (and privileged port).

The images should mostly work fine with this, known issues are:
 - tyk-gateway container will need a pid file path configured for a non-root user accessible path
 - tyk-k8s container should specify a non-privileged port for the injector webhook with relevant changes to the service

**Comment by sedkis** [comment]
@excieve I wonder how this plays with Podman, since it is designed to run containers non-root?  Would doing a simple substitute for Docker to Podman achieve the same behaviour?

**Comment by excieve** [comment]
@sedkis Not directly related in this case.

Kubernetes abstracts the actual runtime (could be Docker Engine, CRI-O, containerd, etc). This task is to set the context for k8s as to how it should run the containers, whichever the actual runtime.

The Helm charts have not much to do over choosing this or that runtime (or at least shouldn't in the general case).

As a side note, with podman, when running in rootless mode you'd still need to make sure that the container is actually able to do that (i.e. not using any system tools/features that require root) or it'll fail.

**Comment by excieve** [comment]
This is not stale.

**Comment by vesko-tyk** [comment]
This is now implemented in this PR:https://github.com/TykTechnologies/tyk-helm-chart/pull/76
