### ISSUE TITLE
README Link to TIB is broken

### ISSUE THREAD

**Issue by stevenson3** [TykTechnologies/tyk-helm-chart#53]
Current link in readme to Tyk Identity Broker: https://tyk.io/docs/getting-started/key-concepts/tyk-components/identity-broker/

Looks like this has been moved to: https://tyk.io/docs/getting-started/tyk-components/identity-broker/

**Comment by vesko-tyk** [comment]
Thanks for spotting this issue @stevenson3. This is now fixed.
