### ISSUE TITLE
MongoDB auth fails when following instructions

### ISSUE THREAD

**Issue by kazvictor** [TykTechnologies/tyk-helm-chart#59]
I'm following the instructions in order to try out Tyk, I got held up for a while with auth to MongoDB failing. After some time I found out it was related to setting `replicaSet.enabled=true` See: https://github.com/helm/charts/issues/15244 
It works and I was able to continue with trial after removing `replicaSet.enabled=true`

**Comment by vesko-tyk** [comment]
@kazvictor I can't replicate this MongoDB auth fail. One possible problem could be that for MongoDB installation we recommend using bitnami/mongodb chart as stated in the docs, while in the ticket from helm repo linked above they're using stable/mongodb chart which could cause the behaviour you're seeing. Will close the issue, please reopen if this needs more attention.
