### ISSUE TITLE
Allow to configure the redis.database value for tyk-hybrid

### ISSUE THREAD

**Issue by ldealmei** [TykTechnologies/tyk-helm-chart#71]
Currently when deploying Tyk with the Helm Chart, `storage.database` is hard-coded to 0.

If this database index is already in use it seems to cause issues of sync with the gateway.
I could not understand exactly what was the issue.

But manually changing the database index to 1 fixed it.

Being able to configure it via the charts `values.yaml` would allow for more flexibility and a more stable deployment setup.

**Comment by vesko-tyk** [comment]
This is now implemented with this PR: https://github.com/TykTechnologies/tyk-helm-chart/pull/120
