### ISSUE TITLE
Tyk-Hybrid installation of tyk-k8s isn't/wasn't obvious enough

### ISSUE THREAD

**Issue by gabeio** [TykTechnologies/tyk-helm-chart#74]
I spent a few days trying to get tyk-hybrid to accept ingress definitions, before I came to the realization that tyk-k8s wasn't installed and needed to be installed for the ingress to work. While `https://github.com/TykTechnologies/tyk-helm-chart/blob/master/tyk-hybrid/templates/NOTES.txt` does state that it needs to be installed, that seems to be the only place that the requirement is mentioned. As this is fairly important to the operation of this system I'd like to propose adding it to the read me so it smacks you in the face that it should be installed _separately_ from the `tyk-hybrid` or `tyk-pro` installation.

I think I overlooked the helm output primarily because it looked so similar to what I had just run (`helm install tyk-hybrid -f ./values_hybrid.yaml ./tyk-hybrid -n tyk-hybrid`).

I can make a PR to help make this more clear (and maybe having this issue searchable can save someone else's time in the future as well 😄 )

**Comment by vesko-tyk** [comment]
Tyk-k8s has been deprecated. For further detail on how to configure Tyk as an Ingress Gateway, or how to manage APIs using the Kubernetes API, please refer to our Tyk Operator documentation here: https://github.com/TykTechnologies/tyk-operator/
