### ISSUE TITLE
TLS Cert has expired

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk-helm-chart#88]
https://github.com/TykTechnologies/tyk-helm-chart/tree/master/tyk-headless/certs

The certificates in the headless chart has expired

<img width="802" alt="Screenshot 2021-03-08 at 16 03 44" src="https://user-images.githubusercontent.com/1465130/110346956-007a6300-8028-11eb-8634-1d5df2dbe368.png">

**Comment by vesko-tyk** [comment]
This is now resolved with this PR: https://github.com/TykTechnologies/tyk-helm-chart/pull/89
