### ISSUE TITLE
Pods dont automatically pick up config changes

### ISSUE THREAD

**Issue by joshblakeley** [TykTechnologies/tyk-helm-chart#9]
We can address this in our deployment yamls with this trick https://helm.sh/docs/developing_charts/#automatically-roll-deployments-when-configmaps-or-secrets-change

This will save having to `helm upgrade --recreate-pods` each time we want new configuration propagated to the pods.

**Comment by excieve** [comment]
Should be kept open, simple to implement.

**Comment by vesko-tyk** [comment]
This is now implemented with this PR: https://github.com/TykTechnologies/tyk-helm-chart/pull/84
