### ISSUE TITLE
Remove dependency on namespace "tyk"

### ISSUE THREAD

**Issue by sedkis** [TykTechnologies/tyk-helm-chart#92]
If you try to deploy `tyk-pro` outside of the `tyk` namespace, it gives you many errors related to namespace "tyk". 

You should be able to install it anywhere.  If I have multiple namespaces in my team, this is problematic.

Can we please remove the hard-coded "tyk" namespace

**Comment by joshblakeley** [comment]
Can you share those errors please @sedkis - the chart should be deployable in any given namespace

**Comment by gernest** [comment]
Installling the charts in non `tyk` namespace gives the error

Error: namespaces "tyk" not found

I'm preparing a PR in a moment

**Comment by gernest** [comment]
I came across this installing `tyk-pro`
