### ISSUE TITLE
Tyk Developer Portal doesn't work with default Helm Chart deployment Tyk-Pro

### ISSUE THREAD

**Issue by sedkis** [TykTechnologies/tyk-helm-chart#99]
After running the Tyk Helm Chart, I don't have a working Portal.

1. I add my license to the `values.yaml`
2. everything else is default

I run the following commands:
```bash
	$ kubectl create namespace tyk
	$ kubectl apply -f deploy/dependencies/mongo.yaml -n tyk
	$ kubectl apply -f deploy/dependencies/redis.yaml -n tyk
	$ helm install tyk-pro ./tyk-pro -n tyk --wait
```

Everything works correctly, but no Portal.  I try to access:
![image](https://user-images.githubusercontent.com/8964621/111674335-48507580-87f2-11eb-9331-c6b29539db04.png)

And it loads infinitely.

## WORKAROUND
in order to get it to work, I have to 
1. set the portal domain in the ui
2. restart my dashboard pods
3. create a default page template

**Comment by frknbrbr** [comment]
We also could not access the Developer Portal. We are having the same issue. What do you mean by creating a default page template? @sedkis

**Comment by serkanbingol** [comment]
We have reinstall fixed tyk-pro helm chart today, but we have also same problem.  We set portal and dashbord url with ingress but we can't access developer portal.

**Comment by buger** [comment]
As for creating default page pls refer to https://tyk.io/docs/tyk-cloud/initial-portal-config/

**Comment by abhishiekgowtham** [comment]
#105 should resolve this issue.

**Comment by sedkis** [comment]
Works as per #105, thanks @abhishiekgowtham
